source ‘https://github.com/CocoaPods/Specs.git’

platform :ios, '7.0'

target 'SUIMVVMDemo' do
pod 'AFNetworking', '>= 3.0'
pod 'MJExtension'
pod 'FMDB'
pod 'SUIUtils', :git => 'https://github.com/randomprocess/SUIUtils'
pod 'MJRefresh'
end
